name: tsacdop
description: An open source podcast player.

version: 0.7.0-beta.5+48
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_animated: ^3.0.0
  audio_session: ^0.1.0
  cached_network_image: ^3.1.0
  color_thief_dart: ^0.1.0
  confetti: ^0.8.0
  cupertino_icons: ^1.0.2
  crypto: ^3.0.1
  dio_cookie_manager: ^3.1.1
  dio: ^5.7.0
  extended_nested_scroll_view: ^6.2.1
  feature_discovery: ^0.14.0
  file_picker: ^8.1.4
  flutter_html: ^3.0.0-beta.2
  fluttertoast: ^8.0.9
  flutter_isolate: ^2.0.0
  flutter_linkify: ^6.0.0
  flutter_file_dialog: ^3.0.2
  flare_flutter: ^3.0.2
  fl_chart: ^0.69.0
  line_icons: ^2.0.1
  flutter_media_metadata: ^1.0.0+1
  marquee: ^2.0.0
  google_fonts: ^6.2.1
  image: ^4.3.0
  json_serializable: ^6.8.0
  json_annotation: ^4.0.1
  permission_handler: ^11.3.1
  provider: ^6.0.0
  sqflite: ^2.0.0+3
  state_notifier: ^1.0.0
  tuple: ^2.0.0
  url_launcher: ^6.0.3
  uuid: ^4.5.1
  workmanager: ^0.5.0
  audio_service: ^0.18.0
  just_audio: ^0.9.23
  equatable: ^2.0.0
  path_provider: ^2.0.1
  http_parser: ^4.0.0
  collection: ^1.15.0-nullsafety.4
  shared_preferences_android: ^2.0.12
  path_provider_android: ^2.0.14
  material_color_utilities: ^0.11.1
  dynamic_color: ^1.4.0
  lints: ^5.0.0
  focused_menu: ^1.0.5
  linkify: ^5.0.0
  webfeed: ^0.7.0
  flutter_cache_manager: any
  shared_preferences: any
  path: any
  html: any
  cookie_jar: any
  convert: any
  rxdart: any
  connectivity_plus: ^6.1.0
  device_info_plus: ^11.1.1
  share_plus: ^10.1.2
  flutter_downloader: ^1.11.8
  intl: any
  xml: any
dependency_overrides:
  linkify:
    git:
      url: https://github.com/lojcs/linkify.git                        # Tsacdop fork, updated to 5.0.0
  focused_menu:
    git:
      url: https://github.com/lojcs/focused_menu.git                   # Tsacdop fork, updated to 1.0.5
  webfeed:
    git:
      url: https://github.com/lojcs/webfeed.git                        # Tsacdop fork, updated to 0.7.0. Not updated to webfeed_plus
  flutter_media_metadata:
    git:
      url: https://github.com/MihMihai/flutter_media_metadata_enhanced # Updated fork, original stale
  feature_discovery:
    git:
      url: https://github.com/JahezAcademy/feature_discovery           # Updated fork, original stale
  flare_flutter:
    git:
      url: https://github.com/ykh09242/Flare-Flutter                   # Updated fork, new version of flare is rive
      path: flare_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  dependency_validator: ^4.1.1

flutter:
  assets:
    - assets/
  uses-material-design: true
flutter_intl:
  enabled: true
  localizely:
    project_id: bde4e9bd-4cb2-449b-9de2-18f231ddb47d
